#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           50
bspc config top_padding          50
bspc config left_padding         650
bspc config right_padding        650
bspc config automatic_scheme longest_side

bspc config border_width 3
bspc config focused_border_color "#cba6f7"
bspc config normal_border_color "#454358"

xrandr --output DP-2 --mode 5120x1440 --rate 120
setxkbmap -layout us -variant intl

~/.config/bspwm/auto_padding.sh &

# Polybar
~/.config/polybar/launch.sh &

# feh
~/.config/feh/set_background.sh &

# conky
conky &

# compositor
picom &

